show databases;
use database2;
show tables;
select * from opiskelija;
insert into opiskelija values(null,'Roope','Ankka','TVT24SPL',null);
select * from opiskelija;
insert into opiskelija values(null,'Aku','Ankka','TVT24SPL',null);
select * from opiskelija;
select * from opintojakso;
insert into opintojakso values(null,'Java-ohjelmointi','TS20044',5);
select * from opiskelija;
insert into opiskelija values(null,'Mikki','Hiiri','TVT24SPO','Ankkalinna 316');
select * from arviointi;
insert into opintojakso values(1,3,5,curdate());
select * from opiskelija;
